### ISSUE TITLE
Error when trying to use bot token 

### ISSUE THREAD

**Issue by ThonkPT** [Yaekith/OpenDiscordHaxx#1]
![image](https://user-images.githubusercontent.com/57663757/99434479-c107f980-2906-11eb-892d-e0be2f86e118.png)
are bot tokens just not supported?

**Comment by kamikos** [comment]
Bot tokens should look like this "Bot " + token
also remember that it can't do some things that user token can do

**Comment by faith** [comment]
As the guy said above bot tokens must have have formatting of "Bot (token)" and it can't do some things as user tokens as users are different from bots of course and don't cover such wide scope of features as users. Close the issue if no further help is needed.
